### ISSUE TITLE
Solve Problem on waking up the object to get the scales

### ISSUE THREAD

**Issue by jensens** [plone/plone.scale#26]
**Problem:**

In order to get a scale or generate its tag one must wake up the context object which has the image. In listings this leads to a vast amount of getObject calls.

**How it works now**

``plone.scale`` created the scale and stores it as an annotation of the object. 

**Proposed Solution**

Rough sketch:

- Additional store a mapping ``(content UID, image hash)`` as an OOBTree as an annotation at portal level on scale creation. 
- Remove the mapping on cleanup
- Provide an utility to lookup scales UIDs 
- Also (not in here), provide convinicence API for same features - i.e. tag creation - ass @@images does now directly on the object. Idea: As ``images`` adapter between catalog brain and request providing the same interface as ``@@images``.

**Comment by davisagli** [comment]
I think this is no longer needed, now that image scales are available in catalog metadata.
