### ISSUE TITLE
ScalesDict should be a ScalesTree

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.scale#41]
This package stores the scales in to a `PersistentDict` based object.
https://github.com/plone/plone.scale/blob/dedf66a90c3e0dd1df7d3e971a4b293951def610/plone/scale/storage.py#L53

AFAIK everytime we need a scale we are effectively waking up from the DB the whole PersistentDict.

I am wondering if this instead should be an OOBTree based class.

**Comment by ale-rt** [comment]
Note this consideration was triggered by this entry in the slowlog:
```
  File "/var/zope/.buildout/eggs/plone.scale-3.0.3-py3.7.egg/plone/scale/storage.py", line 178, in scale
    info = self.get_info_by_hash(key)
  File "/var/zope/.buildout/eggs/plone.scale-3.0.3-py3.7.egg/plone/scale/storage.py", line 171, in get_info_by_hash
    for value in self.storage.values():
```
which seems not optimized code as well but that is another story.

CC @tisto @datakurre

**Comment by ale-rt** [comment]
@gotcha I see you implemented Conflict resolution for `ScalesDict` in https://github.com/plone/plone.scale/pull/7.
Do you think the same code will apply as well to an OOBTree or that OOBTree can handle the `ConflitError` itself?

**Comment by gotcha** [comment]
@ale-rt 
- #7 might be the proof that I did not know enough about BTrees to think to use them.
- I see `BTrees` implement `_p_resolveConflict`. 
- My knowledge of ZODB and BTrees is a bit shallow but I think that your proposal not only makes sense but should work.

Now, code only will prove it. 😉

**Comment by ale-rt** [comment]
> Now, code only will prove it.

Yeah I plan to work on this. But first I would like to know if my premises make sense :)
Thanks for replying!

**Comment by datakurre** [comment]
@ale-rt You may be entering a rabbit hole :-) I recall that the code goes through all scales on every write to clean up outdated scales.

On the other hand, it's only metadata of the scales. I doubt it wakes up scale blobs until you really need them. Consider the possibility that it could be more performant to wake up that one relatively small PersistentDict than many BTree buckets (unless you optimize scale cleanup).

**Comment by ale-rt** [comment]
Thanks for your precious input @datakurre, makes lot of sense!
I will close this for now.
