### ISSUE TITLE
Modernize plone.scale, make AnnotationStorage an adapter

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.scale#44]
Low hanging fruit:

- Make it Python 3.7+, Plone 6 only. (Well, might work on 5.2 Py 3 as well. The package itself does not do anything with the rest of Plone, expect importing `plone.testing` in the tests.)
- black, isort5, pyupgrade
- Remove the `docs` directory and the `[sphinx]` extra. The last real update is from 2010. The text from the index has been included in the readme, and the rest is not interesting, and outdated. Hosted here: https://pythonhosted.org/plone.scale/
- GitHub Actions may be nice here, since the package does not use Plone, and advertises itself as supporting "Zope 2, grok and other systems build on using the Zope ToolKit".

And then the interesting one: register `AnnotationStorage` as an adapter.

`AnnotationStorage` is [defined](https://github.com/plone/plone.scale/blob/3.1.2/plone/scale/storage.py#L116-L117) like this:

```
@implementer(IImageScaleStorage)
class AnnotationStorage(MutableMapping):
```

But there is no zcml, so this is never registered as an adapter.
So `plone.namedfile` has to [call `AnnotationStorage` directly](https://github.com/plone/plone.namedfile/blob/5.6.0/plone/namedfile/scaling.py#L496-L499) instead of doing an adapter lookup.
With an adapter lookup in place, I can register a different adapter for tiles. Currently `plone.app.tiles` defines its [own annotation storage](https://github.com/plone/plone.app.tiles/blob/3.2.2/plone/app/tiles/imagescaling.py#L30-L44) which it uses in [`publishTraverse`](https://github.com/plone/plone.app.tiles/blob/3.2.2/plone/app/tiles/imagescaling.py#L92) and in [`scale`](https://github.com/plone/plone.app.tiles/blob/3.2.2/plone/app/tiles/imagescaling.py#L178).  This is one of the reasons that `plone.app.tiles` copies over so many code from `plone.namedfile`.

If we register `AnnotationStorage` as an adapter, we solve this problem. And it seems logical.

What do you think?

**Comment by mauritsvanrees** [comment]
@plone/framework-team Any objections to this in Plone 6.0?
PLIP seems overkill, it is a minor feature.

**Comment by tisto** [comment]
@mauritsvanrees if that's an additional feature I don't see any problem or the need for a PLIP. Though, I'd really like to have this for Plone 5.2/Python3 as well.

**Comment by ale-rt** [comment]
I am fine with that :)

There is no zcml in this package because it was meant to stay generic and to be used out of plone.
I do not know if you want to add the adapter registration in the zcml in this package (which does not seem to be a problem to me) or in some other package (which one? I have no idea!).

**Comment by tisto** [comment]
My 2c: I guess it is time to stop suspecting that anyone is using plone.* packages outside of the plone world. We are putting considerable effort into imaginary people. Small, reusable packages help with keeping things separated and are easier to test. That's a valid point. The outside usage of plone.* packages has never been a valid point in history IMHO.

There is a reason I choose plone.restapi over plone.app.restapi. :)

I am not saying we have to put things upside down and get rid of this package madness. Though, we should not put effort into something that has been a lost cause for ages.

**Comment by ale-rt** [comment]
> We are putting considerable effort into imaginary people.

:rofl:

**Comment by tisto** [comment]
@ale-rt that quote is from @datakurre. Just to give proper credits here. :)

**Comment by mauritsvanrees** [comment]
I wanted to put the new zcml in plone.scale, and then in CMFPlone or in plone.namedfile we could load this zcml.
But we can keep plone.scale pure Python, and since plone.namedfile would be the main user of the new adapter, it is simpler to put the zcml only in plone.namedfile.

So far, this should be fine in 5.2, because this does nothing until we really use it. But if nothing uses it, it is not needed.

The change makes possible that plone.namedfile does an adapter lookup instead of directly calling `AnnotationStorage`. But I would hesitate to accept this in 5.2. Nothing *should* change, but if people have made patches/overrides/customizations, things could inadvertently break.

So I would do this in Plone 6 only.

**Comment by tisto** [comment]
@mauritsvanrees can we still make the plone.scale package itself compatible with Plone 5.2 so that people can use it if they want to? We don't have to officially ship it with Plone 5.2 but having it as an option would be good to have.

**Comment by mauritsvanrees** [comment]
@tisto Since `plone.scale` is basically Plone-agnostic, we could let tox/GHA run the tests on Python 3.6+.

**Comment by mauritsvanrees** [comment]
I have released this in plone.scale 4.0.0a1 and the adapter in plone.namedfile 6.0.0a2.
