### ISSUE TITLE
Are image scales thrown away needlessly?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.scale#55]
I have heard community members complain about image scales being purged from the storage when there is no reason. I am doing some tests, also adding unit tests, and so far it seems to go how I expect:

- Add a portal_type with an image field to Plone and view two scales, let's say on `@@images/image/mini` and `@@images/image/preview`.
- Edit the image and only change the title.
- View the scales: you get the cached scales.
- Edit the image and upload a different image.
- View the mini scale: the old mini scale is explicitly removed and a new one is generated. The preview scale is kept.
- View the preview scale 24 hours later via the unique url: you get the cached scale, even though it is outdated.
- View the large scale: you have not viewed this yet, so a new scale is generated. This triggers cleaning up outdated scales.
- The cached preview scale is removed because it is older than 24 hours and is outdated.
- The cached mini scale is kept even though it is older than 24 hours: it is not outdated.

So that seems fine.

The only other thing I fear could be true, is:

- You have a portal_type with two image fields.
- Upload to image field 1, save, generate a scale.
- Upload to image field 2, maybe after 24 hours, save, generate a scale.
- This might throw away scales from image field 1, although they are not outdated.

Is that maybe the case?

@datakurre I think at least you reported this.

**Comment by datakurre** [comment]
@mauritsvanrees Yes.

I recall that we had strong caching policy with at least 24 hour max-time with Varnish, and this behavior resulted cached HTML with broken image scale URLs every now and then.

This did require multiple conditions to happen, as you described. Including our Varnish to drop cached image scales due to limited memory.
