### ISSUE TITLE
Stop testing master branch with Plone 5.2

### ISSUE THREAD

**Issue by davisagli** [plone/plone.scale#62]
The master branch of plone.scale is only used for Plone 6. We should stop testing with the version pins from Plone 5.2 and declare that we've removed support for it.

**Comment by mauritsvanrees** [comment]
I tried keeping it compatible, just like plone.namedfile. I would like to keep it this way, even though core 5.2 does not use it. I want to use it in a customer project.

**Comment by davisagli** [comment]
Okay, that is fine with me.
